name: t2d_gene_prioritization
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - openpyxl
  - joblib
  - tqdm
  - pip
  - pip:
      - biopython
      - lightgbm
      - xgboost
      - torch
      - transformers
